site_name: Soar documentation
repo_url: http://github.com/SoarGroup/Documentation
repo_name: SoarGroup/Documentation
copyright: SoarGroup &copy;

theme:
  name: material
  locale: en
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: Images/soar.png
  custom_dir: overrides

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - extra
  - tables
  - mdx_math
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

nav:
  - Soar:
      - index.md
      - Research:
          - Publications: "soar/Publications.md"
          - Research Groups: "soar/ResearchGroups.md"
          - Academic Institutions: "soar/OtherAcademicInstitutions.md"
          - Commercial Soar Organizations: "soar/CommercialSoarOrganizations.md"
  - Soar Manual:
      - soar_manual/index.md
      - Introduction:  "soar_manual/01_Introduction.md"
      - The Soar Architecture: "soar_manual/02_TheSoarArchitecture.md"
      - Syntax of Soar Programs: "soar_manual/03_SyntaxOfSoarPrograms.md"
      - Procedural Knowledge Learning: "soar_manual/04_ProceduralKnowledgeLearning.md"
      - Reinforcement Learning: "soar_manual/05_ReinforcementLearning.md"
      - Semantic Memory: "soar_manual/06_SemanticMemory.md"
      - Episodic Memory: "soar_manual/07_EpisodicMemory.md"
      - Spatial Visual System: "soar_manual/08_SpatialVisualSystem.md"
      - Soar User Interface: "soar_manual/09_SoarUserInterface.md"
      - Blocksworld: "soar_manual/blocksworld.md"
  - Explanations:
      - explanations/index.md
  - Tutorials:
      - tutorials/index.md
      - Official Soar Tutorials:
          - "tutorials/soar_tutorial/index.md"
  - HowTo Guides:
      - how_to/index.md
      - Building Soar and ROS1: "how_to/BuildingSoarRos.md"
  - Reference:
      - reference/index.md
      - Command Line Interface: 
        - "reference/cli/index.md"
        - alias: "reference/cli/cmd_alias.md"
        - trace: "reference/cli/cmd_trace.md"
        - help: "reference/cli/cmd_help.md"
        - sp: "reference/cli/cmd_sp.md"
        - load: "reference/cli/cmd_load.md"
        - gp: "reference/cli/cmd_gp.md"
        - wm: "reference/cli/cmd_wm.md"
        - rl: "reference/cli/cmd_rl.md"
        - default_wme_depth: "reference/cli/cmd_default_wme_depth.md"
        - stop_soar: "reference/cli/cmd_stop_soar.md"
        - alias: "reference/cli/cmd_alias.md"
        - echo: "reference/cli/cmd_echo.md"
        - command_to_file: "reference/cli/cmd_command_to_file.md"
        - unalias: "reference/cli/cmd_unalias.md"
        - epmem: "reference/cli/cmd_epmem.md"
        - clog: "reference/cli/cmd_clog.md"
        - visualize: "reference/cli/cmd_visualize.md"
        - preference: "reference/cli/cmd_preferences.md"
        - excise: "reference/cli/cmd_excise.md"
        - production: "reference/cli/cmd_production.md"
        - wma: "reference/cli/cmd_wma.md"
        - smem: "reference/cli/cmd_smem.md"
        - chunk: "reference/cli/cmd_chunk.md"
        - soar: "reference/cli/cmd_soar.md"
        - run: "reference/cli/cmd_run.md"
        - svs: "reference/cli/cmd_svs.md"
        - explain: "reference/cli/cmd_explain.md"
        - init_soar: "reference/cli/cmd_init_soar.md"
        - decide: "reference/cli/cmd_decide.md"
        - print: "reference/cli/cmd_print.md"
        - debug: "reference/cli/cmd_debug.md"
        - stats: "reference/cli/cmd_stats.md"
        - timers: "reference/cli/cmd_timers.md"
        - watch: "reference/cli/cmd_watch.md"
        - save: "reference/cli/cmd_save.md"
        - max_nil_output_cycles: "reference/cli/cmd_max_nil_output_cycles.md"
        - file_system: "reference/cli/cmd_file_system.md"
        - output: "reference/cli/cmd_output.md"
  - Tag Index: "soar/tags.md"

plugins:
  - search
  - img2figv2
  - tags:
      tags_file: soar/tags.md
