name: Generate PDF Documenatation

on: 
  push:
    branches:
      development

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    container: pandoc/latex:latest
    steps:
      - uses: actions/checkout@v3
      - run: ./docs/Manual/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output